---
title: Papers
---

# 2025

- Kumar, C., Herrera-Gerena, J., Just, J., Darr, M., Jannesari, A. (2026). A Novel Unsupervised Contrastive Learning Approach for Efficient Object Lookup and Retrieval. In: Arai, K. (eds) Intelligent Systems and Applications. IntelliSys 2025. Lecture Notes in Networks and Systems, vol 1660. Springer, Cham. https://doi.org/10.1007/978-3-032-07109-5_36

- Kumar, C., Herrera-Gerena, J., Just, J., Darr, M., Jannesari, A. (2026). Learning Location-Aware Visual Representations Through Anchor-Based Contrastive Learning. In: Arai, K. (eds) Intelligent Systems and Applications. IntelliSys 2025. Lecture Notes in Networks and Systems, vol 1660. Springer, Cham. https://doi.org/10.1007/978-3-032-07109-5_18

- KUMAR, C., 2025. Learning to Detect Objects with Unsupervised Learning. Order No. 31998925 ed. United States -- Iowa: Iowa State University Dissertations & Theses @ Iowa State University; ProQuest Dissertations & Theses Global. ISBN 9798286430598.

# 2024

- Khan, Inzamam, Wajid Shakeel Ahmed, Shafqat Shad, Chandan Kumar, Muhammad Usman, Milad Jasemi, and Khuarm Shafi. "Determine Intraday Trading Currency's Trend Framework Evidence From Machine Learning Techniques." International Journal of Business Intelligence Research (IJBIR) 15, no. 1 (2024): 1-15.

- Khan, Inzamam, Wajid Shakeel Ahmed, Shafqat Shad, Chandan Kumar, Muhammad Usman, Milad Jasemi, and Khuarm Shafi. "Determine Intraday Trading Currency's Trend Framework Evidence From Machine Learning Techniques." International Journal of Business Intelligence Research (IJBIR) 15, no. 1 (2024): 1-15.

- Kumar, Chandan, Ali Jannesari, and Matthew Darr. "Discerning self-supervised learning and weakly supervised learning." In The Second Tiny Papers Track at ICLR 2024. 2024.

# 2023

- Kumar, Chandan, and Ali Jannesari. "Optimal deep learning model for uavs: A case study." In 2023 26th International Symposium on Wireless Personal Multimedia Communications (WPMC), pp. 51-57. IEEE, 2023.


# 2022

- Kumar, Chandan, Yamini Mathur, and Ali Jannesari. "Efficient volume estimation for dynamic environments using deep learning on the edge." In 2022 IEEE International Parallel and Distributed Processing Symposium Workshops (IPDPSW), pp. 995-1002. IEEE, 2022.

- J. K. Francis, C. Kumar, J. Herrera-Gerena, K. Kumar and M. J. Darr, "Deep Learning and Pattern-based Methodology for Multivariable Sensor Data Regression," 2022 21st IEEE International Conference on Machine Learning and Applications (ICMLA), Nassau, Bahamas, 2022, pp. 748-753, doi: 10.1109/ICMLA55696.2022.00125. keywords: {Training;Deep learning;Computer vision;Computational modeling;Crops;Computer architecture;Pattern recognition;artificial intelligence;neural networks;Regression analysis;agriculture},

- Kumar, Chandan. "Efficient volume analysis for dynamic environments using Deep Learning." Master's thesis, Iowa State University, 2022.

# 2021

- Vaddi, Subrahmanyam, Dongyoun Kim, Chandan Kumar, Shafqat Shad, and Ali Jannesari. "Efficient Object Detection Model for Real-time UAV Application." Computer and Information Science 14, no. 1 (2021).
<!-- references -->

# 2023

- Mogere E, Mwaura E, Waithaka M, Mutua V, Mugao M, von Csefalvay C, Mukamati D (2023). Juvenile polyposis syndrome: A case report. _Clinical Case Reports_ 2023;**11**:e6798. doi:[10.1002/ccr3.6798](https://doi.org/10.1002/ccr3.6798)

# 2022

- Mutua V, Henry B, von Csefalvay C, Cheruiyot I, Vikse J, Lippi G, Bundi B, Mong’are N (2022). Tocilizumab in addition to standard of care in the management of COVID-19: A meta-analysis of RCTs. _Acta Bio Medica: Atenei Parmensis_ 2022;**93**. doi:[10.23750/abm.v93i1.12208](https://doi.org/10.23750/abm.v93i1.12208)

- Bundi B, Mutua V, Cheruiyot I, Munguti J, von Csefalvay C, Nurani K, Ogeng’o J (2022). The Unusual High Origin Radial Artery in a Black Kenyan Population: A Cadaveric Study. _Ethiopian Journal of Health Sciences_ 2022;**32**. doi:[10.4314/ejhs.v32i2.25](https://doi.org/10.4314/ejhs.v32i2.25)

- Munguti J, Mutua V, Cheruiyot I, von Csefalvay C, Opare-Addo P, Kiko N, Wanjiru R (2022). Tuberculous polyserositis in endemic areas with an emphasis on empiric therapy: A case report. _Medicine: Case Reports and Study Protocols_ 2022;**3**:e0221. doi:[10.1097/MD9.0000000000000221](https://doi.org/10.1097/MD9.0000000000000221)

# 2021

- von Csefalvay C (2021). VAERS data reveals no increased risk of neuroautoimmune adverse events from COVID-19 vaccines. _medRxiv_. doi:[10.1101/2021.06.13.21258851](https://doi.org/10.1101/2021.06.13.21258851).

- von Csefalvay C (2021). Early evidence for the safety of certain COVID-19 vaccines using empirical Bayesian modeling from VAERS. _medRxiv_. doi:[10.1101/2021.06.10.21258589](https://doi.org/10.1101/2021.06.10.21258589).

- von Csefalvay C (2021). A case-control study of autoimmune AEFIs following COVID-19 vaccination reported to VAERS. _medRxiv_. doi:[10.1101/2021.07.06.21260074](https://doi.org/10.1101/2021.07.06.21260074).

- von Csefalvay C (2021). Anaphylactic events in mRNA vaccines: a reporting case-control study. _medRxiv_. doi:[10.1101/2021.07.19.21260714](https://doi.org/10.1101/2021.07.19.21260714).

- Mutua V, Mong’are N, Bundi B, von Csefalvay C, Oriko D, Kitunguu P (2021). Sudden bilateral lower limb paralysis with dural ectasia in Neurofibromatosis type 1: A case report. _Medicine: Case Reports and Study Protocols_ 2021;**2**:e0165. doi:[10.1097/MD9.0000000000000165](https://doi.org/10.1097/MD9.0000000000000165)

- Mpekethu N, Mongare N, Mutua V, Wangari M, von Csefalvay C, Ojuka D (2021). Knowledge and attitudes of undergraduate medical students in Kenya towards solid organ donation and transplantation: Are Africa’s future clinicians prepared?. _African Journal of Nephrology_ 2021;**24**:89--94. doi:[10.21804/24-1-4843](https://doi.org/10.21804/24-1-4843)

# 2020

- von Csefalvay C, Foldi T (2020). PAWS: Towards a globally integrated outbreak surveillance system for public health. _Zenodo_ 2020. doi:[10.5281/zenodo.3782871](https://doi.org/10.5281/zenodo.3782871)

- Foldi T, von Csefalvay C, Perez N (2020). Jampi: Efficient matrix multiplication in Spark using barrier execution mode. _Big Data and Cognitive Computing_ 2020;**4**:32. doi:[10.3390/bdcc4040032](https://doi.org/10.3390/bdcc4040032)

- von Csefalvay C (2020). Statistical dynamics of social distancing in SARS-CoV-2 as a differential game. _arXiv_ [2007.13734](https://arxiv.org/abs/2007.13734).

- von Csefalvay C (2020). Vector quantisation and partitioning of COVID-19 temporal dynamics in the United States. _arXiv_ [2008.00559](https://arxiv.org/abs/2008.00559).

# 2019

- von Csefalvay C (2019). Novel quantitative indicators of digital ophthalmoscopy image quality. _arXiv_ [1903.02695](https://arxiv.org/abs/1903.02695).

# 2015

- von Csefalvay C (2015). Ecological metrics of diversity in understanding social media. _arXiv_ [1501.07621](https://arxiv.org/abs/1501.07621).

# 2009

- von Csefalvay C (2009). On Good Intentions and Poor Outcomes: A Critical Retrospective on Chester v Afshar. _UC Dublin L. Rev._ 2009;**9**:46.

# 2007

- von Csefalvay C (2007). Taunts, Chapati Pans and the Case of the Reasonable Glue-Sniffer: An Examination of the Normative Test in Provocation after Smith and Holley. _Cambridge Student Law_ 2007:45--52. doi:[10.2139/ssrn.1334048](https://doi.org/10.2139/ssrn.1334048)


